import React from "react";

/**
 * Copyright (c) 2022 Dell Inc., or its subsidiaries. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

export const DATA = {
    rows: [
        {
            ip: '192.168.0.1',
            serial: '1234ECG88TGS',
            model: 'PI-12345672',
            template: 'ECS EX400',
            networking: 'DHCP',
            role: 'Data, Monitor',

        }
    ],
    hugeData: [
        {
            ip: '192.168.0.1',
            serial: '1234ECG88TGS',
            model: 'PI-12345672',
            template: 'ECS EX400',
            networking: 'DHCP',
            role: 'Data, Monitor',
        }
    ],
}
for(let i=0;i<5;i++){
    DATA.rows.push({
        ip: '192.168.0.'+i,
        serial: '1234ECG88TGS',
        model: 'PI-12345672',
        template: 'ECS EX400',
        networking: 'DHCP',
        role: 'Data, Monitor',
    })
}
for(let i=0;i<150;i++){
    DATA.hugeData.push({
        ip: '192.168.0.'+i,
        serial: '1234ECG88TGS',
        model: 'PI-12345672',
        template: 'ECS EX400',
        networking: 'DHCP',
        role: 'Data, Monitor',
    })
}
//  expandable component.
export const ExpandedComponent = ({data}) => <pre>{JSON.stringify(data.title, null, 2)}</pre>;
export const DETAILDATA = {
    data: [
            {
                  "status": "good",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB",
                },
                {
                  "status": "bad",
                  "name": "Disk 2",
                  "slot": 1,
                  "serial": "HJSFJ7891",
                  "type": "Read/Write",
                  "capacityUsed": "180 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "1.2 GB",
                  "availableRAIDDiskSpace": "5 GB",
                  "negotiatedSpeed": "3 Gbps",
                  "capableSpeed": "3 Gbps",
                  "serialNumber": "GJHGJCKG2d",
                  "revision": "KJ53",
                  "productId": "ST8000JH02052JH",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "Yes",
                  "deviceDescription": "Disk 2 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB",
                },
                {
                  "status": "suspect",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB",
                },
                {
                  "status": "good",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB",
                },
                {
                  "status": "bad",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "suspect",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "good",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "bad",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "suspect",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "good",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "bad",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "suspect",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "good",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "good",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "good",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
                },
                {
                  "status": "good",
                  "name": "Disk 1",
                  "slot": 1,
                  "serial": "LPQW7891",
                  "type": "Read/Write",
                  "capacityUsed": "100 GiB",
                  "controller": 1,
                  "blockSize": "512 bytes",
                  "operationalState": "N/A",
                  "remainingDriveLife": "N/A",
                  "progress": "N/A",
                  "usedRAIDDiskSpace": "0 GB",
                  "availableRAIDDiskSpace": "0 GB",
                  "negotiatedSpeed": "6 Gbps",
                  "capableSpeed": "6 Gbps",
                  "serialNumber": "ZAK1CKG2d",
                  "revision": "PB53",
                  "productId": "ST8000NM02052FF",
                  "manufacturer": "ATA",
                  "partNumber": "TH092WDWGJHDGKFHHKJH",
                  "SASAddress": "0x87694853ACDB",
                  "powerStatus": "Spun Up",
                  "failurePredicted": "No",
                  "deviceDescription": "Disk 1 of 120 blockplane integrated",
                  "capacityAvailable": "200 GiB"
               
                }
          
          
    ]}

    export const issueData = {
        node:[
        {
          "acknowledged": false,
          "clearType": "Auto",
          "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
          "message": "This is a message for update of the application",
          "namespace": "atlantic",
          "reason": "Update",
          "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
        },
        {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          },
          {
            "acknowledged": false,
            "clearType": "Auto",
            "id": "SXNzdWU6ZGVja3MtYXRsYW50aWMtVXBkYXRlLUFwcGxpY2F0aW9uLWF0bGFudGljLWRlY2tz",
            "message": "This is a message for update of the application",
            "namespace": "atlantic",
            "reason": "Update",
            "remedies": ["Restart your cluster!", "Delete your cluster and nuke it!"]
          }
        ]
      }

